[server]
use-ipv4=yes
use-ipv6=yes
enable-dbus=yes
allow-interfaces=eth0,wlan0,uap0,wlan1,usb0,usb1
deny-interfaces=wpan0
ratelimit-interval-usec=500000
ratelimit-burst=500

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=no
publish-domain=yes
disable-user-service-publishing=no
