[Service]
ExecStart=
#ExecStart=/usr/sbin/wpa_supplicant -u -O "DIR=/run/wpa_supplicant GROUP=netdev" 
ExecStart/usr/sbin/wpa_supplicant -u -O "DIR=/run/wpa_supplicant GROUP=netdev" p2p_set disabled 1
