[Service]
ExecStart=
ExecStart=/usr/sbin/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -i wlan0 -u -o nl80211 p2p_set disabled 1 -N -c /etc/wpa_supplicant/wpa_supplicant-uap0.conf -i uap0 -u -o nl80211 p2p_set disabled 1 
